{{config(materialized = 'ephemeral')}}

WITH gold_listings AS(
    SELECT LISTING_ID,PROPERTY_TYPE,ROOM_TYPE,CITY,COUNTRY,ACCOMMODATES,BEDROOMS,BATHROOMS,PRICE_PER_NIGHT,LISTING_CREATED_AT,PRICE_RATEING FROM {{ref('obt')}}
)SELECT * FROM gold_listings