{{config(materialized = 'incremental',unique_key='HOST_ID')}}

SELECT 
HOST_ID,
REPLACE(HOST_NAME,' ','_') AS HOST_NAME,
HOST_SINCE,
IS_SUPERHOST,
RESPONSE_RATE,
CREATED_AT AS HOST_CREATED_AT,
CASE WHEN RESPONSE_RATE>95 THEN 'VERY GOOD'
    WHEN RESPONSE_RATE>80 THEN 'GOOD'
    WHEN RESPONSE_RATE>60 THEN 'FAIR'
    ELSE 'POOR'
END AS RESPONSE_RATE_QUALITY
FROM {{ ref('bronze_hosts') }}
WHERE HOST_CREATED_AT > ( SELECT COALESCE(MAX(HOST_CREATED_AT),'1900-01-01') FROM {{ this }})
