{{config(materialized = 'incremental',unique_key='BOOKING_ID')}}

SELECT 
BOOKING_ID,
LISTING_ID AS BOOKING_LISITNG_ID,
cast(BOOKING_DATE AS TIMESTAMP_NTZ) BOOKING_DATE,
NIGHTS_BOOKED,
BOOKING_AMOUNT,
CLEANING_FEE,
SERVICE_FEE,
BOOKING_STATUS,
CREATED_AT AS BOOKING_CREATED_AT,
{{ multiply('NIGHTS_BOOKED','BOOKING_AMOUNT',2) }} + CLEANING_FEE + SERVICE_FEE AS TOTAL_BOOKING_AMOUNT
FROM {{ ref('bronze_bookings') }}



