models:
  - name: bronze_bookings
    config:
      materialized: table
      schema: bronze
      
    columns:
      - name: BOOKING_AMOUNT
        tests:
          - booking_amount_min:   # generic data-test 
              arguments:
                warn_if: "<=1000"
                error_if: ">=3000"
          - not_null:
              arguments:
                severity : warn
                #severity : warn #error
